# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0002_auto_20170221_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hardware',
            new_name='CallLog',
        ),
    ]
