# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0003_auto_20170221_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[(b'LT', b'Laptop'), (b'TAB', b'Tablet'), (b'PH', b'Mobile Phone'), (b'', b'')], default=b'', max_length=3)),
                ('problem_description', models.TextField(default=b' ', max_length=500)),
                ('error_messages', models.CharField(blank=True, max_length=500)),
                ('file_upload', models.BinaryField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[(b'iNovah', b'iNovah'), (b'Website', b'EPL Website'), (b'', b'')], default=b'', max_length=200)),
                ('system_offline', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=1)),
                ('problem_description', models.CharField(max_length=500)),
                ('steps_replicate_problem', models.CharField(max_length=500)),
                ('file_upload', models.BinaryField()),
            ],
        ),
    ]
