# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0003_auto_20170221_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asgnmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignedBy', models.CharField(default='NULL', max_length=96)),
                ('DateAssign', models.CharField(default='NULL', max_length=10)),
                ('TimeAssign', models.CharField(default='NULL', max_length=8)),
                ('Assignee', models.CharField(default='NULL', max_length=96)),
                ('Description', models.TextField(default='NULL')),
                ('DateAcknow', models.CharField(default='NULL', max_length=10)),
                ('TimeAcknow', models.CharField(default='NULL', max_length=8)),
                ('DateResolv', models.CharField(default='NULL', max_length=10)),
                ('TimeResolv', models.CharField(default='NULL', max_length=8)),
                ('Resolution', models.TextField(default='NULL')),
                ('CallID', models.CharField(default='NULL', max_length=8)),
                ('HEATSeq', models.IntegerField(default=0)),
                ('EMail', models.CharField(default='NULL', max_length=100)),
                ('DTLastMod', models.IntegerField(default=0)),
                ('WhoAcknow', models.CharField(default='NULL', max_length=96)),
                ('WhoResolv', models.CharField(default='NULL', max_length=96)),
                ('TargetTime', models.CharField(default='NULL', max_length=8)),
                ('TargetDate', models.CharField(default='NULL', max_length=10)),
                ('SLAResTime', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('TotalAsgnmntTime', models.IntegerField(default=0)),
                ('CallType', models.CharField(default='NULL', max_length=100)),
                ('ResolveOrder', models.IntegerField(default=0)),
                ('Status', models.CharField(default='NULL', max_length=25)),
                ('ModBy', models.CharField(default='NULL', max_length=50)),
                ('ModDate', models.CharField(default='NULL', max_length=10)),
                ('ModTime', models.CharField(default='NULL', max_length=8)),
                ('TimeUpdate', models.IntegerField(default=0)),
                ('TeamName', models.CharField(default='NULL', max_length=30)),
                ('TempNotes', models.TextField(default='NULL')),
                ('TempTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProbType', models.CharField(default='NULL', max_length=25)),
                ('Description', models.TextField(default='NULL')),
                ('Category', models.CharField(default='NULL', max_length=20)),
            ],
        ),
    ]
