# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0004_asgnmnt_probtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='id',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='CallID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='FirstResolution',
            field=models.CharField(default='NIL', max_length=3),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='Priority',
            field=models.CharField(default='NL', max_length=2),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='SevChanged',
            field=models.CharField(default='NL', max_length=2),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='Yes_No',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
