# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Category',
            new_name='status',
        ),
    ]
