# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epl', '0007_auto_20170322_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='branch',
        ),
    ]
